name : example
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello to the GH-200 Workshops"
      - name: Copy code
        uses: actions/checkout@v6

      - name: List all the files
        run: ls -la
        
      - name: Create ASCII Art
        run: |
          sudo apt -get install -y figlet
          figlet "GH200 COHACK"
          echo "-------------------------"
          figlet -f digital "Github Actions"
          echo "ASCII Act Created"
          
      
